plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "ext/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Integration-style specs naturally have multiple expectations per example
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
